FROM alpine:latest

# Install dependencies
RUN apk add --no-cache --update postfix dovecot ca-certificates git gcc musl-dev linux-headers libmilter-dev

#install python
RUN apk add --update --no-cache python3 python3-dev && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip; pip3 install --no-cache --upgrade pip setuptools

RUN pip3 install zimbraweb git+https://github.com/sdgathman/pymilter

#dovecot config
ADD ./files/dovecot/conf.d/ /etc/dovecot/conf.d/

#copy python scripts
ADD ./files/*.py /srv/zimbraweb/
RUN chmod 777 /srv/zimbraweb/*.py

RUN mkdir /srv/zimbraweb/mnt/ /srv/zimbraweb/logs/; chmod -R 777 /srv/zimbraweb/mnt/; chmod -R 777 /srv/zimbraweb/logs/

VOLUME /srv/zimbraweb/mnt/

# Add crontab to delete auth tokens from memory
RUN crontab -l /cron
RUN echo "* * * * * find /dev/shm/ -name auth_* -type f -perm 444 -mmin +3 -delete" >> /cron
RUN crontab /cron
RUN rm /cron

#### at this point the regular container starts postconf. In this build we will copy the settings from the regular container in its own postfix folder, since the "default" postfix will be the null instance

RUN postconf -e "maillog_file=/var/log/maillog_null"
RUN postconf -e "master_service_disable = inet"
RUN postconf -e "local_transport = error:5.1.1 Mailbox unavailable"
RUN postconf -e "relayhost = [172.17.0.2]"
#RUN postconf -e "authorized_submit_users = root"

####
RUN postmulti -e init
RUN postmulti -I postfix-zimbra -G mta -e create

#postfix config
RUN postconf -c /etc/postfix-zimbra/ -e mynetworks=0.0.0.0/0; postconf -c /etc/postfix-zimbra/ -e "maillog_file=/var/log/maillog_zimbra"; postconf -c /etc/postfix-zimbra/ -e smtpd_sasl_path=private/auth; postconf -c /etc/postfix-zimbra/ -e smtpd_sasl_type=dovecot; postconf -c /etc/postfix-zimbra/ -e smtpd_sasl_auth_enable=yes; postconf -c /etc/postfix-zimbra/ -e smtpd_delay_reject=yes; postconf -c /etc/postfix-zimbra/ -e smtpd_client_restrictions=permit_sasl_authenticated,reject; postconf -c /etc/postfix-zimbra/ -e smtpd_milters=unix:/milter.sock
RUN postconf -c /etc/postfix-zimbra/ -e "smtp_bind_address = 0.0.0.0"; postconf -c /etc/postfix-zimbra/ -e "inet_interfaces = loopback-only"
RUN postconf -c /etc/postfix-zimbra/ -e "smtpd_relay_restrictions ="; postconf -c /etc/postfix-zimbra/ -e "smtpd_recipient_restrictions = permit_mynetworks, reject"
RUN postconf -c /etc/postfix-zimbra/ -e "master_service_disable =" "authorized_submit_users = root"

#add script execution
#https://contrid.net/server/mail-servers/postfix-catch-all-pipe-to-script
RUN touch /etc/postfix-zimbra/virtual_aliases
RUN echo "*  zimbrawebtransport:" > /etc/postfix-zimbra/transport
#zusammen mit -e muss bei echo $ escaped werden
RUN echo -e "zimbrawebtransport   unix  -       n       n       -       -       pipe\n  flags=FR user=nobody argv=/srv/zimbraweb/send_mail.py\n  \${nexthop} \${user} \${sasl_username}" >> /etc/postfix-zimbra/master.cf
RUN echo -e "transport_maps = texthash:/etc/postfix-zimbra/transport\nvirtual_alias_maps = texthash:/etc/postfix-zimbra/virtual_aliases" >> /etc/postfix-zimbra/main.cf

RUN echo -e "submission inet n - y - - smtpd" >> /etc/postfix-zimbra/master.cf; echo -e " -o syslog_name=postfix/submission" >> /etc/postfix-zimbra/master.cf; echo -e " -o smtpd_sasl_auth_enable=yes" >> /etc/postfix-zimbra/master.cf; echo -e " -o smtpd_sasl_path=private/auth" >> /etc/postfix-zimbra/master.cf; echo -e " -o smtpd_client_restrictions=permit_sasl_authenticated,reject" >> /etc/postfix-zimbra/master.cf

RUN postmulti -i postfix-zimbra -e enable

####

# Expose smtp submission port
EXPOSE 587

ADD ./files/start.sh /
RUN chmod +x /start.sh

ADD ./files/tls-multi.sh /tls.sh
RUN chmod +x /tls.sh; mkdir /tls/

CMD ["/start.sh"]